import express from 'express';import {requireAuth} from './auth.js';import * as client from './appsScriptClient.js';import {normalizeTransactions} from './normalize.js';import {filterTx,dashboard} from './analytics.js';import {buildInsights} from './insights.js';
export const router=express.Router();
router.get('/auth/status',(req,res)=>res.json({ok:true,authenticated:!!req.session?.authenticated}));
router.post('/auth/login',(req,res)=>{const {login,password}=req.body||{}; if(login===process.env.APP_LOGIN&&password===process.env.APP_PASSWORD){req.session.authenticated=true;return res.json({ok:true});} res.status(401).json({ok:false,error:'Credenciais inválidas'});});
router.post('/auth/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
router.use(requireAuth);
router.get('/health',async(req,res)=>{try{const h=await client.health();res.json({ok:true,appsScript:h});}catch(e){res.status(500).json({ok:false,error:e.message});}});
router.get('/metadata',async(req,res)=>res.json(await client.getMetadata()));
router.get('/dashboard',async(req,res)=>{const tx=normalizeTransactions((await client.getTransactions()).transactions||[]); const filtered=filterTx(tx,req.query); const d=dashboard(filtered);res.json({ok:true,...d,insights:buildInsights(filtered,d.summaryCards)});});
router.get('/transactions',async(req,res)=>{const tx=normalizeTransactions((await client.getTransactions()).transactions||[]);res.json({ok:true,transactions:filterTx(tx,req.query)});});
router.get('/categories',async(req,res)=>{const tx=filterTx(normalizeTransactions((await client.getTransactions()).transactions||[]),req.query).filter(t=>t.type==='Despesa'); const byCategory=Object.entries(tx.reduce((a,t)=>((a[t.category]=(a[t.category]||0)+t.amount),a),{})).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value);res.json({ok:true,byCategory});});
router.post('/transactions',async(req,res)=>res.json(await client.addTransaction(req.body)));
